---
- name: Deploy DevOps Tools
  hosts: tools
  become: yes
  tasks:
    - name: Install Python Docker library
      apt:
        name: python3-docker
        state: present

    
    - name: Set vm.max_map_count for SonarQube
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        reload: yes

    - name: Start SonarQube Container
      docker_container:
        name: sonarqube
        image: sonarqube:lts-community
        state: started
        restart_policy: always
        ports:
          - "9000:9000"

    - name: Start Nexus Repository
      docker_container:
        name: nexus
        image: sonatype/nexus3
        state: started
        restart_policy: always
        ports:
          - "8081:8081"